# Generated by Django 5.0.6 on 2024-06-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=20)),
                ('nationality', models.DateField()),
                ('course', models.CharField(max_length=30)),
                ('teacher_id', models.PositiveSmallIntegerField(max_length=10)),
                ('account_number', models.CharField(max_length=40)),
                ('date_of_joining', models.DateField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
