# Generated by Django 5.0.6 on 2024-06-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacher_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='nationality',
            field=models.CharField(max_length=20),
        ),
    ]
