# Generated by Django 5.0.6 on 2024-06-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.PositiveSmallIntegerField()),
                ('course_name', models.CharField(max_length=20)),
                ('course_department', models.CharField(max_length=30)),
                ('course_prerequisites', models.CharField(max_length=20)),
                ('teacher_id', models.PositiveSmallIntegerField()),
                ('teacher_first_name', models.CharField(max_length=20)),
                ('teacher_last_name', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=20)),
                ('course_requirements', models.CharField(max_length=30)),
                ('course_capacity', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
