# Generated by Django 5.0.6 on 2024-06-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_prerequisites',
            field=models.CharField(max_length=50),
        ),
    ]
