# Generated by Django 5.0.6 on 2024-06-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.PositiveSmallIntegerField()),
                ('class_name', models.CharField(max_length=30)),
                ('meeting_time', models.CharField(max_length=50)),
                ('teacher', models.PositiveSmallIntegerField()),
                ('enrollment', models.CharField(max_length=20)),
                ('meeting_days', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('class_status', models.CharField(max_length=30)),
                ('class_capacity', models.PositiveSmallIntegerField()),
                ('general_performance', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
