# Generated by Django 5.0.6 on 2024-06-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='meeting_time',
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.TimeField(),
        ),
    ]
