# Generated by Django 5.0.6 on 2024-06-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_alter_class_academic_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='enrollment',
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(max_length=20),
        ),
    ]
